### ISSUE TITLE
client freeze entering world dev environment deobf version 1.4.2

### ISSUE THREAD

**Issue by denbukki** [Azanor/Baubles#182]
i get this error when trying to enter a world.

http://pastebin.com/6j3esLgt

my mod doenst yet implement baubles.
and no other mods used.

**Comment by KiriCattus** [comment]
An issue like this happens happens in the 1.3.8 version of baubles for devs I have a diffrent error tho with a few mods (JEI, Tinkers and the GuideAPI) but nothing that touches Baubles but my mod.

Game loads up fine till you create a world or open a world in single player it just crashes at random points on world load 

https://gist.github.com/ProxyNeko/0e7e76f5f34c4c5a0648d0d6be5530dd

This is the console log from client start to error and freeze. Fingers crossed its fixable as I haven't been able to do much modding till now and would like to port my mods to a few newer versions of MC :)

Forge version: 12.18.3.2185
JEI version: 3.13.2.359
Tinkers version: 2.5.6.435
Mantle version: 1.1.0.jenkins178
GuideAPI version: 2.0.2-45
Baubles Deobf version: 1.3.8
LVN version: 2.0.0 (Mod being developed)

Update:
Thought about trying the full on Baubles-1.10.2-1.3.8.jar mod rather than the deobf version and that works fine for now I can still work with that but no idea what caused the crashes/freeze when you load single player.

**Comment by darkhax** [comment]
This issue is likely caused by baubles using an outdated version of the Minecraft mappings. It should be using stable_29.

**Comment by darkhax** [comment]
As shown above, i've made a pull request to fix this issue. If you're like me and need this fix sooner rather than later, my changes are available on JitPack. Given how my changes don't change any method signatures outside of those obfuscated for vanilla, it should be completely safe to use my fork for testing and building. 

```
		repositories {
			maven { url 'https://jitpack.io' }
		}
```

```
	dependencies {
	        deobfCompile 'com.github.Darkhax-Forked:Baubles:1.10.2-SNAPSHOT'
	}
```

**Comment by ProxyNeko** [comment]
I found a good fix was just using the full on jar file for the mod rather than the deobf jar file that fixed all my issues and I can still access everything I need but thanks for the info!
